############# English navigation ##############

# main menu
[[main]]
weight = 1
url = ""
name = "Page d'accueil"
hasChildren = true

  [[main]]
  parent = "Page d'accueil"
  weight = 1
  url = "homepage/list/"
  name = "List layout"

  [[main]]
  parent = "Page d'accueil"
  weight = 2
  url = "homepage/grid/"
  name = "Grid layout"
  
[[main]]
weight = 3
url = "about/"
name = "À propos"
  
[[main]]
weight = 4
url = "contact/"
name = "Contact"

[[main]]
weight = 5
url = "#"
name = "Pages"
hasChildren = true

  [[main]]
  parent = "Pages"
  weight = 1
  url = "author/"
  name = "Auteur"
  
  [[main]]
  parent = "Pages"
  weight = 2
  url = "tags/"
  name = "Mots clés"
  
  [[main]]
  parent = "Pages"
  weight = 3
  url = "tags/photography/"
  name = "Balise unique"
  
  [[main]]
  parent = "Pages"
  weight = 4
  url = "categories/"
  name = "Catégorie"
  
  [[main]]
  parent = "Pages"
  weight = 5
  url = "categories/lifestyle/"
  name = "Catégorie Unique"
  
  [[main]]
  parent = "Pages"
  weight = 6
  url = "elements/"
  name = "Éléments"

############################# Footer Menu ########################
[[footer]]
weight = 1
url = "about/"
name = "À propos"

[[footer]]
weight = 2
url = "author/"
name = "Auteures"

[[footer]]
weight = 3
url = "privacy/"
name = "Confidentialité"

[[footer]]
weight = 4
url = "terms-conditions/"
name = "termes et conditions"